[general]
# IMPORTANT: Alacritty will first import in order of files provided and than override the import with the settings in this file
import = [
	# "~/.config/alacritty/themes/tomorrownight.toml",
	# "~/.config/alacritty/themes/duotonedark.toml"
	"~/.config/alacritty/local-font.toml"
]

[env]
# define environment vars here, that Alacritty will set

[window]
opacity = 0.95
padding = { x = 5, y = 0 }

[font]
size = 11
offset = { x = 0, y = 2 }




